# Build settings

markdown: kramdown
permalink: none
plugins:             [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

url: 'http://www.avidilumi.github.io'

port: 4000

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		           "Avidi Lumi"
description:	       "Powered by Jekyll with Portfolio Jekyll Theme"
author:              "Lorenzo Scricchio"
