#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
#- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'website made with [Portfolio Jekyll theme](lenpaul.github.io/portfolio-jekyll-theme/)'
  #rel-author: 'https://plus.google.com/u/0/#'
  #rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-149929303-1'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # Avidi Lumi

  Collettivo attivo nella ricerca, la composizione, la pratica e la didattica musicale, con sede a Roma. <br>

  <br>Avidi Lumi (Roma) is a collective working on research, composition, music teaching and practicing.


contact: >
  # Contact

  write us [an email](mailto:info@avidilumi.com) or come to visit at<br>
  via del Casale Rocchi, 39 (Roma)<br>
  
  **Strutture convezionate**

  <br>in arrivo


#-------------------------------
# Work Section

projects:
- {name: 'Seminari di Musica Contemporanea ed Elettroacustica', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Simone Beneventi', folder: 'proj-2', file: 'projects/proj-2.html'}
#- {name: 'Project Three', folder: 'proj-3', file: 'projects/proj-3.html'}
#- {name: 'Project Four', folder: 'proj-4', file: 'projects/proj-4.html'}
#- {name: 'Project Five', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
#- {icon: 'twitter', link: '#'}
- {icon: 'instagram', link: 'https://www.instagram.com/avidilumi/'}
- {icon: 'github', link: 'https://github.com/AvidiLumi'}
- {icon: 'facebook', link: 'https://www.facebook.com/avidilumi/'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
