#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
#- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contacts', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'website made with [Portfolio Jekyll theme](lenpaul.github.io/portfolio-jekyll-theme/)'
  #rel-author: 'https://plus.google.com/u/0/#'
  #rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-149929303-1'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'lorenzoscricchio'

#-------------------------------
# About Section

about: >
  # Avidi Lumi

  Collettivo attivo nella ricerca, la composizione, la pratica e la didattica musicale, con sede a Roma. <br>

  <br>Avidi Lumi (Roma) is a collective working on research, composition, music teaching and practicing.


contact: >
  # Contatti / Contacts

  write us [an email](mailto:info@avidilumi.com) or come to visit at<br>
  via del Casale Rocchi, 39 (Roma)<br>
  there is parking<br>
  <br>
  Con i mezzi/By bus:<br>
  *441* - stop: last stop Casale Rocchi (ID: 79783)<br>
  *211* - stop: Pietralata/Casale Rocchi (ID: 72485)<br>
  *111* - stop: Durantini/Pietralata (ID: 71169) and then walking<br>
  *MB* - stop: Monti Tiburtini and then walking, or other buses<br>

  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2968.276689898361!2d12.542265515479032!3d41.92990547014952!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x132f63122ef774d9%3A0x360c7de91dd13f7e!2sAvidi%20Lumi!5e0!3m2!1sit!2sit!4v1571844539789!5m2!1sit!2sit" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>

  <br>**Strutture convezionate / Affiliated structures**

  <br>in arrivo


#-------------------------------
# Work Section

projects:
- {name: 'Simone Beneventi', folder: '2020gen', file: 'projects/2020-percussionsweek.html'}
- {name: 'Seminari di Musica Contemporanea ed Elettroacustica', folder: '2019nov', file: 'projects/2019nov.html'}
#- {name: 'Project Three', folder: 'proj-3', file: 'projects/proj-3.html'}
#- {name: 'Project Four', folder: 'proj-4', file: 'projects/proj-4.html'}
#- {name: 'Project Five', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/avidilumi/'}
- {icon: 'instagram', link: 'https://www.instagram.com/avidilumi/'}
- {icon: 'github', link: 'https://github.com/AvidiLumi'}
- {icon: 'facebook', link: 'https://www.facebook.com/avidilumi/'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
